version: "3.9"

networks:

  # rete per la comunicazione interna dei containers
  shop-net:
    name: shop-net
    ##########################################
secrets:
  MONGO_ROOT_PW:
    file: lib/secrets/MONGO_ROOT_PW
    ##########################################
volumes:
  shop-vol:
    name: shop-vol

##########################################
services:

  backup:
    image: ildug/mongodump
    restart: unless-stopped
    container_name: db-backup
    depends_on:
      - db
    environment:
      MONGO_ROOT_PW_FILE: /run/secrets/MONGO_ROOT_PW
      USER: root

      HOST: db
      PORT: 27017
      
      # REPLSET: rs0
      # HOSTS: host01.com:27017,host02.com:27017,host03.com:27017
      
      DB: shop
      CRON: "0 4 * * *"

      ARCHIVE: true

    networks:
      - shop-net
    volumes:
      - ./backup:/backup
    secrets:
      - MONGO_ROOT_PW
