name: Build Docker Image

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ildug/mongodump

jobs:
  build:
    name: Build, tag and push to Github Container Registry
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Get Tags
        id: tag
        uses: ildug/get-tag-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker buildx create --driver docker-container --use
          docker buildx build . \
                --file Dockerfile \
                --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
                --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.version }} \
                --platform linux/amd64,linux/arm64/v8 \
                --push
